// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mail.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmailEntry struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	ConfirmedAt          int64    `protobuf:"varint,3,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`
	Optout               bool     `protobuf:"varint,4,opt,name=optout,proto3" json:"optout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailEntry) Reset()         { *m = EmailEntry{} }
func (m *EmailEntry) String() string { return proto.CompactTextString(m) }
func (*EmailEntry) ProtoMessage()    {}
func (*EmailEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0}
}

func (m *EmailEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailEntry.Unmarshal(m, b)
}
func (m *EmailEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailEntry.Marshal(b, m, deterministic)
}
func (m *EmailEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailEntry.Merge(m, src)
}
func (m *EmailEntry) XXX_Size() int {
	return xxx_messageInfo_EmailEntry.Size(m)
}
func (m *EmailEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailEntry.DiscardUnknown(m)
}

var xxx_messageInfo_EmailEntry proto.InternalMessageInfo

func (m *EmailEntry) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EmailEntry) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EmailEntry) GetConfirmedAt() int64 {
	if m != nil {
		return m.ConfirmedAt
	}
	return 0
}

func (m *EmailEntry) GetOptout() bool {
	if m != nil {
		return m.Optout
	}
	return false
}

type InsertEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertEmailRequest) Reset()         { *m = InsertEmailRequest{} }
func (m *InsertEmailRequest) String() string { return proto.CompactTextString(m) }
func (*InsertEmailRequest) ProtoMessage()    {}
func (*InsertEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{1}
}

func (m *InsertEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertEmailRequest.Unmarshal(m, b)
}
func (m *InsertEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertEmailRequest.Marshal(b, m, deterministic)
}
func (m *InsertEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertEmailRequest.Merge(m, src)
}
func (m *InsertEmailRequest) XXX_Size() int {
	return xxx_messageInfo_InsertEmailRequest.Size(m)
}
func (m *InsertEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertEmailRequest proto.InternalMessageInfo

func (m *InsertEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEmailRequest) Reset()         { *m = GetEmailRequest{} }
func (m *GetEmailRequest) String() string { return proto.CompactTextString(m) }
func (*GetEmailRequest) ProtoMessage()    {}
func (*GetEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{2}
}

func (m *GetEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailRequest.Unmarshal(m, b)
}
func (m *GetEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailRequest.Marshal(b, m, deterministic)
}
func (m *GetEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailRequest.Merge(m, src)
}
func (m *GetEmailRequest) XXX_Size() int {
	return xxx_messageInfo_GetEmailRequest.Size(m)
}
func (m *GetEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailRequest proto.InternalMessageInfo

func (m *GetEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type DeleteEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEmailRequest) Reset()         { *m = DeleteEmailRequest{} }
func (m *DeleteEmailRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteEmailRequest) ProtoMessage()    {}
func (*DeleteEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{3}
}

func (m *DeleteEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEmailRequest.Unmarshal(m, b)
}
func (m *DeleteEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEmailRequest.Marshal(b, m, deterministic)
}
func (m *DeleteEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEmailRequest.Merge(m, src)
}
func (m *DeleteEmailRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteEmailRequest.Size(m)
}
func (m *DeleteEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEmailRequest proto.InternalMessageInfo

func (m *DeleteEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UpdateEmailRequest struct {
	EmailEntry           *EmailEntry `protobuf:"bytes,1,opt,name=emailEntry,proto3" json:"emailEntry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateEmailRequest) Reset()         { *m = UpdateEmailRequest{} }
func (m *UpdateEmailRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateEmailRequest) ProtoMessage()    {}
func (*UpdateEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{4}
}

func (m *UpdateEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEmailRequest.Unmarshal(m, b)
}
func (m *UpdateEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEmailRequest.Marshal(b, m, deterministic)
}
func (m *UpdateEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEmailRequest.Merge(m, src)
}
func (m *UpdateEmailRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateEmailRequest.Size(m)
}
func (m *UpdateEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEmailRequest proto.InternalMessageInfo

func (m *UpdateEmailRequest) GetEmailEntry() *EmailEntry {
	if m != nil {
		return m.EmailEntry
	}
	return nil
}

type GetEmailBatchRequest struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Page                 int64    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEmailBatchRequest) Reset()         { *m = GetEmailBatchRequest{} }
func (m *GetEmailBatchRequest) String() string { return proto.CompactTextString(m) }
func (*GetEmailBatchRequest) ProtoMessage()    {}
func (*GetEmailBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{5}
}

func (m *GetEmailBatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailBatchRequest.Unmarshal(m, b)
}
func (m *GetEmailBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailBatchRequest.Marshal(b, m, deterministic)
}
func (m *GetEmailBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailBatchRequest.Merge(m, src)
}
func (m *GetEmailBatchRequest) XXX_Size() int {
	return xxx_messageInfo_GetEmailBatchRequest.Size(m)
}
func (m *GetEmailBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailBatchRequest proto.InternalMessageInfo

func (m *GetEmailBatchRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetEmailBatchRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

type GetEmailResponse struct {
	EmailEntry           *EmailEntry `protobuf:"bytes,1,opt,name=emailEntry,proto3" json:"emailEntry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetEmailResponse) Reset()         { *m = GetEmailResponse{} }
func (m *GetEmailResponse) String() string { return proto.CompactTextString(m) }
func (*GetEmailResponse) ProtoMessage()    {}
func (*GetEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{6}
}

func (m *GetEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailResponse.Unmarshal(m, b)
}
func (m *GetEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailResponse.Marshal(b, m, deterministic)
}
func (m *GetEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailResponse.Merge(m, src)
}
func (m *GetEmailResponse) XXX_Size() int {
	return xxx_messageInfo_GetEmailResponse.Size(m)
}
func (m *GetEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailResponse proto.InternalMessageInfo

func (m *GetEmailResponse) GetEmailEntry() *EmailEntry {
	if m != nil {
		return m.EmailEntry
	}
	return nil
}

type GetEmailBatchResponse struct {
	EmailEntry           []*EmailEntry `protobuf:"bytes,1,rep,name=emailEntry,proto3" json:"emailEntry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetEmailBatchResponse) Reset()         { *m = GetEmailBatchResponse{} }
func (m *GetEmailBatchResponse) String() string { return proto.CompactTextString(m) }
func (*GetEmailBatchResponse) ProtoMessage()    {}
func (*GetEmailBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{7}
}

func (m *GetEmailBatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailBatchResponse.Unmarshal(m, b)
}
func (m *GetEmailBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailBatchResponse.Marshal(b, m, deterministic)
}
func (m *GetEmailBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailBatchResponse.Merge(m, src)
}
func (m *GetEmailBatchResponse) XXX_Size() int {
	return xxx_messageInfo_GetEmailBatchResponse.Size(m)
}
func (m *GetEmailBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailBatchResponse proto.InternalMessageInfo

func (m *GetEmailBatchResponse) GetEmailEntry() []*EmailEntry {
	if m != nil {
		return m.EmailEntry
	}
	return nil
}

func init() {
	proto.RegisterType((*EmailEntry)(nil), "proto.EmailEntry")
	proto.RegisterType((*InsertEmailRequest)(nil), "proto.InsertEmailRequest")
	proto.RegisterType((*GetEmailRequest)(nil), "proto.GetEmailRequest")
	proto.RegisterType((*DeleteEmailRequest)(nil), "proto.DeleteEmailRequest")
	proto.RegisterType((*UpdateEmailRequest)(nil), "proto.UpdateEmailRequest")
	proto.RegisterType((*GetEmailBatchRequest)(nil), "proto.GetEmailBatchRequest")
	proto.RegisterType((*GetEmailResponse)(nil), "proto.GetEmailResponse")
	proto.RegisterType((*GetEmailBatchResponse)(nil), "proto.GetEmailBatchResponse")
}

func init() {
	proto.RegisterFile("mail.proto", fileDescriptor_7cda5f053e74676b)
}

var fileDescriptor_7cda5f053e74676b = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0xb5, 0x2d, 0x10, 0x9c, 0xaa, 0xc8, 0x88, 0x58, 0xd1, 0x03, 0xf6, 0x22, 0xe1, 0x80, 0x11,
	0xcf, 0x26, 0x0a, 0x12, 0xa2, 0xf1, 0x54, 0xe3, 0xc5, 0x0b, 0xa9, 0xed, 0x88, 0x4d, 0xa0, 0x5b,
	0xdb, 0xc5, 0xc4, 0x8f, 0xf6, 0x1f, 0x4c, 0xb7, 0x50, 0xd6, 0x56, 0x85, 0x78, 0x6a, 0xe7, 0xcd,
	0xdb, 0x37, 0xb3, 0xef, 0x2d, 0xc0, 0xd4, 0xf6, 0x26, 0x9d, 0x20, 0x64, 0x9c, 0x61, 0x51, 0x7c,
	0xcc, 0x29, 0xc0, 0x20, 0x46, 0x07, 0x3e, 0x0f, 0x3f, 0x70, 0x07, 0x54, 0xcf, 0x35, 0x94, 0xa6,
	0xd2, 0xda, 0xb4, 0x54, 0xcf, 0xc5, 0x1a, 0x14, 0x29, 0xee, 0x1a, 0xaa, 0x80, 0x92, 0x02, 0x4f,
	0x60, 0xcb, 0x61, 0xfe, 0x8b, 0x17, 0x4e, 0xc9, 0x1d, 0xd9, 0xdc, 0xd0, 0x9a, 0x4a, 0x4b, 0xb3,
	0xf4, 0x14, 0xbb, 0xe6, 0x58, 0x87, 0x12, 0x0b, 0x38, 0x9b, 0x71, 0xa3, 0xd0, 0x54, 0x5a, 0x65,
	0x6b, 0x5e, 0x99, 0x6d, 0xc0, 0x5b, 0x3f, 0xa2, 0x90, 0x8b, 0xa1, 0x16, 0xbd, 0xcd, 0x28, 0xe2,
	0xcb, 0x31, 0x8a, 0x34, 0xc6, 0x3c, 0x85, 0xca, 0x90, 0xd6, 0x21, 0xb6, 0x01, 0x6f, 0x68, 0x42,
	0x9c, 0xd6, 0xe0, 0x0e, 0x01, 0x1f, 0x03, 0xd7, 0xce, 0x70, 0xcf, 0x01, 0x28, 0x75, 0x41, 0x1c,
	0xd0, 0xbb, 0xd5, 0xc4, 0xa8, 0xce, 0xd2, 0x1e, 0x4b, 0x22, 0x99, 0x57, 0x50, 0x5b, 0x6c, 0xd7,
	0xb3, 0xb9, 0xf3, 0x2a, 0x8d, 0x75, 0xd8, 0xcc, 0xe7, 0x42, 0x45, 0xb3, 0x92, 0x02, 0x11, 0x0a,
	0x81, 0x3d, 0x26, 0xe1, 0xa3, 0x66, 0x89, 0x7f, 0x73, 0x00, 0xbb, 0xcb, 0xfb, 0x45, 0x01, 0xf3,
	0x23, 0xfa, 0xcf, 0x22, 0x77, 0xb0, 0x9f, 0x59, 0xe4, 0x17, 0x2d, 0x6d, 0xa5, 0x56, 0xf7, 0x53,
	0x85, 0x4a, 0x5c, 0x79, 0xfe, 0x78, 0x14, 0x51, 0xf8, 0xee, 0x39, 0x84, 0x7d, 0xd0, 0xa5, 0xc8,
	0xf0, 0x70, 0xae, 0x90, 0x8f, 0xb1, 0x71, 0x30, 0x6f, 0x65, 0x6f, 0x65, 0x6e, 0xe0, 0x25, 0x94,
	0x17, 0x28, 0xd6, 0x73, 0xb4, 0x95, 0xc7, 0xfb, 0xa0, 0x4b, 0x09, 0xa7, 0x3b, 0xe4, 0x53, 0x5f,
	0x21, 0x22, 0x45, 0x9f, 0x8a, 0xe4, 0x9f, 0xc3, 0x5f, 0x22, 0xf7, 0xb0, 0xfd, 0xcd, 0x6d, 0x3c,
	0xca, 0x70, 0xe5, 0xc7, 0xd0, 0x38, 0xfe, 0xb9, 0xb9, 0x50, 0xeb, 0xed, 0x3d, 0x55, 0x63, 0xf8,
	0x21, 0xb1, 0xfa, 0x4c, 0x90, 0x9f, 0x4b, 0xe2, 0x73, 0xf1, 0x15, 0x00, 0x00, 0xff, 0xff, 0x4d,
	0x24, 0x20, 0xad, 0xae, 0x03, 0x00, 0x00,
}
